# Generated by Django 2.0.5 on 2018-05-13 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_date_in', models.DateTimeField(null=True)),
                ('estimated_date_out', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('type_of_room', models.CharField(choices=[('S', 'Стандарт'), ('M', 'Полулюкс'), ('L', 'Люкс')], default='S', max_length=1)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(default=datetime.datetime(2018, 5, 13, 16, 35, 3, 478712))),
                ('date_out', models.DateTimeField(null=True)),
                ('payment_form', models.CharField(choices=[('C', 'Наличный расчет'), ('M', 'MasterCard'), ('O', 'Другое'), ('V', 'Visa')], default='O', max_length=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Reservation')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='client',
            name='payment_form',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client'),
        ),
    ]
